<?php
header('Content-Type: application/json; charset=utf-8');

// =========================
// 1. MANEJO DE ERRORES
// =========================
set_error_handler(function ($errno, $errstr, $errfile, $errline) {
    echo json_encode([
        "success" => false,
        "message" => "Error de PHP: $errstr en $errfile:$errline"
    ]);
    exit;
});

set_exception_handler(function ($ex) {
    echo json_encode([
        "success" => false,
        "message" => "Excepción: " . $ex->getMessage()
    ]);
    exit;
});

// =========================
// 2. VALIDAR reCAPTCHA
// =========================
$secret = "6LddYhEsAAAAALTm2rvo9p-kHdK8jqbbghUeLyvz"; // CLAVE SECRETA
$response = $_POST["g-recaptcha-response"] ?? "";

if (!$response) {
    echo json_encode(["success" => false, "message" => "Por favor completa el reCAPTCHA."]);
    exit;
}

$verify = file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret={$secret}&response={$response}");
$captcha_result = json_decode($verify, true);

if (!$captcha_result["success"]) {
    echo json_encode(["success" => false, "message" => "❌ Error: Verificación reCAPTCHA fallida."]);
    exit;
}

// =========================
// 3. CONEXIÓN A ORACLE
// =========================
$usuario = "USUARIO";
$contrasena = "Usuario12345";
$cadena_conexion = "localhost/XE";

$conn = oci_connect($usuario, $contrasena, $cadena_conexion);

if (!$conn) {
    $e = oci_error();
    echo json_encode(["success" => false, "message" => "❌ Error de conexión: " . $e['message']]);
    exit;
}

// =========================
// 4. OBTENER DATOS
// =========================
$nombre = $_POST['nombre'] ?? '';
$apellido = $_POST['apellido'] ?? '';
$tipo_documento = $_POST['tipo_documento'] ?? '';
$numero_documento = $_POST['numero_documento'] ?? '';
$edad = $_POST['edad'] ?? '';
$email = $_POST['email'] ?? '';
$dudas = $_POST['dudas'] ?? '';

// VALIDAR CAMPOS OBLIGATORIOS
if (empty($nombre) || empty($apellido) || empty($tipo_documento) || empty($numero_documento)) {
    echo json_encode(["success" => false, "message" => "Faltan datos obligatorios."]);
    oci_close($conn);
    exit;
}

// =========================
// 5. CREAR TABLA SI NO EXISTE
// =========================
$sql_tabla = "
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE table_name = 'REGISTRO';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE REGISTRO (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR2(100),
                apellido VARCHAR2(100),
                tipo_documento VARCHAR2(20),
                numero_documento VARCHAR2(30),
                edad NUMBER,
                email VARCHAR2(100),
                dudas VARCHAR2(500)
            )
        ';
    END IF;
END;";

$tabla_stmt = oci_parse($conn, $sql_tabla);
oci_execute($tabla_stmt);

// =========================
// 6. INSERTAR REGISTRO
// =========================
$sql_insert = "
INSERT INTO REGISTRO
(nombre, apellido, tipo_documento, numero_documento, edad, email, dudas)
VALUES (:nombre, :apellido, :tipo_documento, :numero_documento, :edad, :email, :dudas)
";

$stmt = oci_parse($conn, $sql_insert);

oci_bind_by_name($stmt, ":nombre", $nombre);
oci_bind_by_name($stmt, ":apellido", $apellido);
oci_bind_by_name($stmt, ":tipo_documento", $tipo_documento);
oci_bind_by_name($stmt, ":numero_documento", $numero_documento);
oci_bind_by_name($stmt, ":edad", $edad);
oci_bind_by_name($stmt, ":email", $email);
oci_bind_by_name($stmt, ":dudas", $dudas);

$result = oci_execute($stmt, OCI_COMMIT_ON_SUCCESS);

// =========================
// 7. RESPUESTA FINAL
// =========================
if ($result) {
    echo json_encode(["success" => true, "message" => "Registro guardado correctamente."]);
} else {
    $e = oci_error($stmt);
    echo json_encode(["success" => false, "message" => "❌ Error al insertar: " . $e['message']]);
}

oci_free_statement($stmt);
oci_close($conn);
?>
